# -*- coding: utf-8 -*-
# [MOSAICODE PROJECT]
#
"""
This module contains the JavascriptTemplate class.
"""
from mosaicode.model.codetemplate import CodeTemplate

class Html(CodeTemplate):
    """
    This class contains methods related the JavascriptTemplate class.
    """
    # ----------------------------------------------------------------------

    def __init__(self):
        CodeTemplate.__init__(self)
        self.name = "webaudio"
        self.language = "javascript"
        self.description = "Javascript / webaudio code template"
        self.extension = ".html"
        self.command = "chromium-browser $dir_name$$filename$$extension$\n"
        self.code_parts = ["onload", "function", "declaration", "execution", "html"]
        self.code = r"""<html>
<head>
<meta http-equiv="Cache-Control" content="no-store" />
<title>Generated by Mosaicode</title>
</head>
<body onload='onload_function();'>
<script>
function onload_function(){
$single_code[onload]$
}
var context = new (window.AudioContext || window.webkitAudioContext)();
$single_code[function]$
//declaration block
$code[declaration]$
//connections
$connections$
//function calls
$code[execution]$
</script>
<! deallocation block --!>
$code[html]$
</body>
</html>
"""

# -------------------------------------------------------------------------
